// Données des utilisateurs
export const users = [
    {
        id: '1',
        name: 'John KABERA',
        email: 'john.kabera@email.com',
        phone: '+2348012345678',
        location: 'Kigali, Rwanda',
        profileImage:
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        role: 'buyer' as const,
        joinedDate: '2023-05-15',
        cartItems: ['1', '2'],
        favoriteProducts: ['2', '7', '11'],
        orders: ['101', '102'],
        isVerified: true,
        preferences: {
            categories: ['Fruits', 'Vegetables'],
            notifications: true,
            language: 'en',
            currency: 'NGN',
        },
    },
    {
        id: '2',
        name: 'Makenga Ibrahim',
        email: 'Makenga.ibrahim@email.com',
        phone: '+250802345678',
        location: 'Kirehe, Rwanda',
        profileImage:
            'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop',
        role: 'seller' as const,
        businessName: "Makenga's Farm",
        joinedDate: '2022-11-20',
        products: ['1', '6'],
        rating: 4.5,
        totalSales: 245,
        isVerified: true,
        bankDetails: {
            accountName: "Makenga's Farm",
            accountNumber: '0123456789',
            bankName: 'GTBank',
        },
    },
    {
        id: '3',
        name: 'Adaora Nwari',
        email: 'adaora.n@email.com',
        phone: '+250884567890',
        location: 'Nyagasamba, Rwanda',
        profileImage:
            'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
        role: 'buyer_seller' as const,
        businessName: 'Ada Agro Coop',
        joinedDate: '2023-01-10',
        products: ['2', '12'],
        cartItems: ['4'],
        favoriteProducts: ['1', '5'],
        orders: ['103'],
        rating: 4.8,
        totalSales: 156,
        isVerified: true,
    },
    {
        id: '4',
        name: 'Emeka Okoro',
        email: 'emeka.okoro@email.com',
        phone: '+250794567891',
        location: 'Rwamagana, Rwanda',
        profileImage:
            'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
        role: 'buyer' as const,
        joinedDate: '2024-02-28',
        cartItems: ['3'],
        favoriteProducts: ['10'],
        orders: [],
        isVerified: false,
        preferences: {
            categories: ['Livestock', 'Dairy'],
            notifications: true,
            language: 'en',
            currency: 'NGN',
        },
    },
    {
        id: '5',
        name: 'Fatima Bello',
        email: 'fatima.bello@email.com',
        phone: '+250785679012',
        location: 'Kabarondo, Rwanda',
        profileImage:
            'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
        role: 'seller' as const,
        businessName: 'GreenField Ltd',
        joinedDate: '2023-08-05',
        products: ['3', '8'],
        rating: 4.3,
        totalSales: 89,
        isVerified: true,
        bankDetails: {
            accountName: 'GreenField Ltd',
            accountNumber: '9876543210',
            bankName: 'Access Bank',
        },
    },
];

// Données des catégories
export const categories = [
    {
        id: '1',
        name: 'All',
        active: true,
        icon: '📦',
        color: '#10B981',
        productCount: 12,
    },
    {
        id: '2',
        name: 'Vegetables',
        active: false,
        icon: '🥦',
        color: '#22C55E',
        productCount: 4,
    },
    {
        id: '3',
        name: 'Fruits',
        active: false,
        icon: '🍎',
        color: '#EF4444',
        productCount: 3,
    },
    {
        id: '4',
        name: 'Grains',
        active: false,
        icon: '🌾',
        color: '#F59E0B',
        productCount: 2,
    },
    {
        id: '5',
        name: 'Tubers',
        active: false,
        icon: '🥔',
        color: '#8B5CF6',
        productCount: 1,
    },
    {
        id: '6',
        name: 'Livestock',
        active: false,
        icon: '🐐',
        color: '#EC4899',
        productCount: 1,
    },
    {
        id: '7',
        name: 'Dairy',
        active: false,
        icon: '🥚',
        color: '#3B82F6',
        productCount: 1,
    },
    {
        id: '8',
        name: 'Spices',
        active: false,
        icon: '🌶️',
        color: '#F97316',
        productCount: 0,
    },
];

// Données des produits Fresh Arrivals
export const freshArrivals = [
    {
        id: '1',
        name: 'Organic Roma Tomatoes',
        price: 450,
        unit: 'kg',
        seller: "Musa's Farm",
        sellerId: '2',
        imageUrl:
            'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.5,
        reviews: 24,
        category: 'Vegetables',
        categoryId: '2',
        description:
            'Fresh organic tomatoes from local farms, perfect for salads and cooking.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1-2 days',
        minimumOrder: 1,
        tags: ['organic', 'fresh', 'local'],
        createdAt: '2024-01-15',
    },
    {
        id: '2',
        name: 'Sweet Yellow Mango',
        price: 1200,
        unit: 'crate',
        seller: 'Ada Agro Coop',
        sellerId: '3',
        imageUrl:
            'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop',
        isFavorite: true,
        rating: 4.8,
        reviews: 36,
        category: 'Fruits',
        categoryId: '3',
        description: 'Sweet and juicy yellow mangoes, harvested at peak ripeness.',
        quantity: 1,
        inStock: true,
        deliveryTime: '2-3 days',
        minimumOrder: 1,
        tags: ['sweet', 'tropical', 'ripe'],
        createdAt: '2024-01-10',
    },
    {
        id: '3',
        name: 'Fresh Sweet Corn',
        price: 200,
        unit: 'cob',
        seller: 'GreenField Ltd',
        sellerId: '5',
        imageUrl:
            'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.3,
        reviews: 18,
        category: 'Grains',
        categoryId: '4',
        description: 'Freshly harvested sweet corn, perfect for boiling or grilling.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1 day',
        minimumOrder: 5,
        tags: ['sweet', 'fresh', 'corn'],
        createdAt: '2024-01-18',
    },
    {
        id: '4',
        name: 'White Cassava Tubers',
        price: 5000,
        unit: 'bag',
        seller: 'Oyo Farmers Union',
        sellerId: '6',
        imageUrl:
            'https://images.unsplash.com/photo-1615485730217-68297e412453?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.6,
        reviews: 42,
        category: 'Tubers',
        categoryId: '5',
        description: 'High quality cassava tubers for garri production and cooking.',
        quantity: 1,
        inStock: true,
        deliveryTime: '3-4 days',
        minimumOrder: 1,
        tags: ['cassava', 'tubers', 'garri'],
        createdAt: '2024-01-05',
    },
];

// Tous les produits
export const allProducts = [
    ...freshArrivals,
    {
        id: '5',
        name: 'African Spinach (Efo)',
        price: 350,
        unit: 'bunch',
        seller: 'Fresh Veggies Co',
        sellerId: '7',
        imageUrl:
            'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop',
        isFavorite: true,
        rating: 4.4,
        reviews: 29,
        category: 'Vegetables',
        categoryId: '2',
        description: 'Fresh African spinach leaves, rich in iron and vitamins.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1 day',
        minimumOrder: 2,
        tags: ['spinach', 'leafy', 'healthy'],
        createdAt: '2024-01-12',
    },
    {
        id: '6',
        name: 'Fresh Carrots',
        price: 300,
        unit: 'kg',
        seller: "Musa's Farm",
        sellerId: '2',
        imageUrl:
            'https://images.unsplash.com/photo-1598170845058-78131a90f4bf?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.2,
        reviews: 15,
        category: 'Vegetables',
        categoryId: '2',
        description: 'Organic fresh carrots, crunchy and sweet.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1-2 days',
        minimumOrder: 1,
        tags: ['carrots', 'organic', 'crunchy'],
        createdAt: '2024-01-14',
    },
    {
        id: '7',
        name: 'Basmati Rice',
        price: 2500,
        unit: 'bag',
        seller: 'Grain Masters',
        sellerId: '8',
        imageUrl:
            'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
        isFavorite: true,
        rating: 4.7,
        reviews: 56,
        category: 'Grains',
        categoryId: '4',
        description: 'Premium quality basmati rice, perfect for special occasions.',
        quantity: 1,
        inStock: true,
        deliveryTime: '2-3 days',
        minimumOrder: 1,
        tags: ['rice', 'basmati', 'premium'],
        createdAt: '2024-01-08',
    },
    {
        id: '8',
        name: 'Green Peppers',
        price: 150,
        unit: 'kg',
        seller: 'GreenField Ltd',
        sellerId: '5',
        imageUrl:
            'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.1,
        reviews: 12,
        category: 'Vegetables',
        categoryId: '2',
        description: 'Fresh green bell peppers, great for salads and stir-fries.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1 day',
        minimumOrder: 2,
        tags: ['peppers', 'bell', 'green'],
        createdAt: '2024-01-16',
    },
    {
        id: '9',
        name: 'Pineapples',
        price: 800,
        unit: 'piece',
        seller: 'Tropical Fruits Ltd',
        sellerId: '9',
        imageUrl:
            'https://images.unsplash.com/photo-1550268562-1dd93bc3c9f9?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.5,
        reviews: 31,
        category: 'Fruits',
        categoryId: '3',
        description: 'Sweet tropical pineapples, imported from the best farms.',
        quantity: 1,
        inStock: true,
        deliveryTime: '3-4 days',
        minimumOrder: 1,
        tags: ['pineapple', 'tropical', 'sweet'],
        createdAt: '2024-01-09',
    },
    {
        id: '10',
        name: 'Goat Meat',
        price: 3500,
        unit: 'kg',
        seller: 'Halal Meat Suppliers',
        sellerId: '10',
        imageUrl:
            'https://images.unsplash.com/photo-1603048297172-80d69f1f5e43?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.6,
        reviews: 48,
        category: 'Livestock',
        categoryId: '6',
        description: 'Fresh halal goat meat, properly slaughtered and packaged.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1 day',
        minimumOrder: 0.5,
        tags: ['meat', 'goat', 'halal'],
        createdAt: '2024-01-17',
    },
    {
        id: '11',
        name: 'Fresh Eggs',
        price: 1200,
        unit: 'crate',
        seller: 'Poultry Farm Ltd',
        sellerId: '11',
        imageUrl:
            'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=300&fit=crop',
        isFavorite: true,
        rating: 4.3,
        reviews: 27,
        category: 'Dairy',
        categoryId: '7',
        description: 'Farm fresh eggs, rich in protein and nutrients.',
        quantity: 1,
        inStock: true,
        deliveryTime: '1-2 days',
        minimumOrder: 1,
        tags: ['eggs', 'fresh', 'protein'],
        createdAt: '2024-01-13',
    },
    {
        id: '12',
        name: 'Plantain',
        price: 600,
        unit: 'bunch',
        seller: 'Ada Agro Coop',
        sellerId: '3',
        imageUrl:
            'https://images.unsplash.com/photo-1615485500607-1758f56c2c8a?w=400&h=300&fit=crop',
        isFavorite: false,
        rating: 4.4,
        reviews: 33,
        category: 'Fruits',
        categoryId: '3',
        description: 'Ripe plantain bunches, perfect for frying or boiling.',
        quantity: 1,
        inStock: true,
        deliveryTime: '2-3 days',
        minimumOrder: 1,
        tags: ['plantain', 'ripe', 'bunch'],
        createdAt: '2024-01-11',
    },
];

// Données des paniers
export const cartItems = [
    {
        id: '1',
        productId: '2',
        productName: 'Sweet Yellow Mango',
        price: 1200,
        quantity: 2,
        unit: 'crate',
        seller: 'Ada Agro Coop',
        sellerId: '3',
        imageUrl:
            'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop',
        inStock: true,
    },
    {
        id: '2',
        productId: '7',
        productName: 'Basmati Rice',
        price: 2500,
        quantity: 1,
        unit: 'bag',
        seller: 'Grain Masters',
        sellerId: '8',
        imageUrl:
            'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
        inStock: true,
    },
    {
        id: '3',
        productId: '3',
        productName: 'Fresh Sweet Corn',
        price: 200,
        quantity: 10,
        unit: 'cob',
        seller: 'GreenField Ltd',
        sellerId: '5',
        imageUrl:
            'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop',
        inStock: true,
    },
    {
        id: '4',
        productId: '4',
        productName: 'White Cassava Tubers',
        price: 5000,
        quantity: 1,
        unit: 'bag',
        seller: 'Oyo Farmers Union',
        sellerId: '6',
        imageUrl:
            'https://images.unsplash.com/photo-1615485730217-68297e412453?w=400&h=300&fit=crop',
        inStock: true,
    },
];

// Données des commandes
export const orders = [
    {
        id: '101',
        userId: '1',
        items: [
            {
                productId: '1',
                productName: 'Organic Roma Tomatoes',
                quantity: 2,
                price: 450,
            },
            { productId: '5', productName: 'African Spinach', quantity: 3, price: 350 },
        ],
        totalPrice: 1950,
        status: 'delivered',
        orderDate: '2024-01-10',
        deliveryDate: '2024-01-12',
        deliveryAddress: '123 Lagos Street, Lagos Island, Lagos',
        paymentMethod: 'card',
        trackingNumber: 'TRK123456789',
        sellerNames: ["Musa's Farm", 'Fresh Veggies Co'],
    },
    {
        id: '102',
        userId: '1',
        items: [
            {
                productId: '2',
                productName: 'Sweet Yellow Mango',
                quantity: 1,
                price: 1200,
            },
        ],
        totalPrice: 1200,
        status: 'shipped',
        orderDate: '2024-01-15',
        deliveryDate: '2024-01-18',
        deliveryAddress: '123 Lagos Street, Lagos Island, Lagos',
        paymentMethod: 'transfer',
        trackingNumber: 'TRK987654321',
        sellerNames: ['Ada Agro Coop'],
    },
    {
        id: '103',
        userId: '3',
        items: [
            { productId: '10', productName: 'Goat Meat', quantity: 1.5, price: 3500 },
            { productId: '11', productName: 'Fresh Eggs', quantity: 1, price: 1200 },
        ],
        totalPrice: 6450,
        status: 'confirmed',
        orderDate: '2024-01-18',
        deliveryDate: '2024-01-19',
        deliveryAddress: '456 Enugu Road, Enugu',
        paymentMethod: 'card',
        trackingNumber: 'TRK456789123',
        sellerNames: ['Halal Meat Suppliers', 'Poultry Farm Ltd'],
    },
];

// Données des notifications
export const notifications = [
    {
        id: '1',
        userId: '1',
        title: 'Order Shipped',
        message: 'Your order #102 has been shipped and is on its way!',
        type: 'order',
        read: false,
        date: '2024-01-16T10:30:00',
        data: { orderId: '102' },
    },
    {
        id: '2',
        userId: '1',
        title: 'New Promotion',
        message: 'Get 20% off on all fruits this weekend! Use code: FRUIT20',
        type: 'promotion',
        read: true,
        date: '2024-01-15T14:20:00',
        data: { promotionId: '1' },
    },
    {
        id: '3',
        userId: '2',
        title: 'New Order Received',
        message: 'You have received a new order for Organic Roma Tomatoes',
        type: 'order',
        read: false,
        date: '2024-01-18T09:15:00',
        data: { orderId: '104', productId: '1' },
    },
    {
        id: '4',
        userId: '3',
        title: 'Product Review',
        message: 'John Chukwuma left a 5-star review for your Sweet Yellow Mango',
        type: 'message',
        read: true,
        date: '2024-01-14T16:45:00',
        data: { productId: '2', reviewId: '201' },
    },
];

// Données des messages/chat
export const chats = [
    {
        id: '1',
        participants: ['1', '3'], // John and Adaora
        lastMessage: 'Hello, is the mango still available?',
        lastMessageTime: '2024-01-18T14:30:00',
        unreadCount: 2,
        productId: '2',
    },
    {
        id: '2',
        participants: ['1', '2'], // John and Amina
        lastMessage: 'Thanks for the delivery!',
        lastMessageTime: '2024-01-12T11:20:00',
        unreadCount: 0,
        orderId: '101',
    },
];

// Données des avis/reviews
export const reviews = [
    {
        id: '201',
        productId: '2',
        userId: '1',
        userName: 'John Chukwuma',
        userImage:
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
        rating: 5,
        comment: 'Excellent quality! The mangoes were sweet and fresh. Will order again!',
        date: '2024-01-14',
        helpful: 12,
    },
    {
        id: '202',
        productId: '1',
        userId: '4',
        userName: 'Emeka Okoro',
        userImage:
            'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        rating: 4,
        comment: 'Good tomatoes, but delivery took longer than expected.',
        date: '2024-01-13',
        helpful: 3,
    },
];

// Données de navigation
export const navItems = [
    { id: '1', icon: 'Home', label: 'Home', active: true },
    { id: '2', icon: 'Market', label: 'Market' },
    { id: '3', icon: 'Cart', label: 'Cart', badgeCount: 3 },
    { id: '4', icon: 'Chat', label: 'Chat', badgeCount: 2 },
    { id: '5', icon: 'Profile', label: 'Profile' },
];

// Données des promotions
export const promotions = [
    {
        id: '1',
        title: 'Weekend Special',
        description: 'Get 20% off on all fruits',
        code: 'FRUIT20',
        validUntil: '2024-12-31',
        color: '#10B981',
        discountPercentage: 20,
        minimumPurchase: 2000,
        applicableCategories: ['Fruits'],
    },
    {
        id: '2',
        title: 'New Farmer Bonus',
        description: 'Free delivery on first order',
        code: 'NEWFARM',
        validUntil: '2024-11-30',
        color: '#3B82F6',
        discountPercentage: 0,
        freeDelivery: true,
    },
    {
        id: '3',
        title: 'Bulk Purchase',
        description: 'Buy 3 get 1 free on vegetables',
        code: 'VEGGIE3+1',
        validUntil: '2024-12-15',
        color: '#8B5CF6',
        buyQuantity: 3,
        freeQuantity: 1,
        applicableCategories: ['Vegetables'],
    },
];

// Export par défaut
export default {
    users,
    categories,
    freshArrivals,
    allProducts,
    cartItems,
    orders,
    notifications,
    chats,
    reviews,
    navItems,
    promotions,
};
